version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    network_mode: host
    volumes:
      - mongodb_data_container:/data/db

  bmg-frontend:
    image: alivx/bmg:frontend
    container_name: bmg-frontend
    ports:
      - 3000:3000
  bmg-backend:
    image: alivx/bmg:backend
    container_name: bmg-backend
    environment:
      - connectionString=mongodb-primary
    ports:
      - 3001:3001
    network_mode: host


volumes:
  mongodb_master_data:
    driver: local
networks:
  bmgnetwork:
