version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    network_mode: host
    volumes:
      - mongodb_data_container:/data/db

  backend:
    image: alivx/bmg:backend
    container_name: backend
    ports:
      - 3001:3001
    network_mode: host

  frontend:
    image: alivx/bmg:frontend
    container_name: frontend
    ports:
      - 3000:3000



volumes:
  mongodb_data_container: